name: K6 Load Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  k6_test:
    name: Run k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Baixa o binário oficial diretamente (mais confiável em CI)
      - name: Setup k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -L | tar -xz --strip-components 1
          sudo mv k6 /usr/local/bin/k6

      - name: Run k6 test
        run: k6 run ./tests/loadTest.js